on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Build & Release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build project
        uses: mvkvl/github-action-build@master
        with:
          builder: .github/build
      - uses: actions/upload-artifact@v1
        with:
          name: aws-s3-uploader.tar.gz
          path: target/aws-s3-uploader.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: aws-s3-uploader.tar.gz
      - name: Create release
        uses: mvkvl/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        uses: mvkvl/github-upload-release-artifacts-action@master
        with:
          args: "aws-s3-uploader.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
